services:
  dynamicstore-minio:
    image: quay.io/minio/minio
    container_name: dynamicstore-minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    hostname: dynamicstore-minio
    networks: 
      - test-network
    volumes:
      - minio-data:/data

  dynamicstore-mongo:
    image: mongo:4.0-xenial
    container_name: dynamicstore-mongo
    hostname: dynamicstore-mongo
    volumes:
      - mongo-data:/data
    ports:
      - "27021:27017"
    networks: 
      - test-network

  dynamicstore-mysql:
    image: mysql
    container_name: dynamicstore-mysql
    hostname: dynamicstore-mysql
    command:
      - --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - TZ=Asia/Kolkata
    ports:
      - "3308:3306"
    networks:
      - test-network

volumes:
  minio-data:
  mongo-data:

networks:
  test-network:
    driver: bridge
    ipam:
     config:
        - subnet: 192.168.0.191/28
    
