services:
  staticstore-minio:
    image: quay.io/minio/minio
    container_name: staticstore-minio
    command: server /data --console-address ":9001"
    ports:
      - "9002:9000"
      - "9003:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    hostname: staticstore-minio
    networks: 
      - test-network
    volumes:
      - minio-data:/data

  staticstore-mongo:
    image: mongo:4.0-xenial
    container_name: staticstore-mongo
    hostname: staticstore-mongo
    volumes:
      - mongo-data:/data
    ports:
      - 27022:27017
    networks:
      - test-network

volumes:
  minio-data:
  mongo-data:

networks:
  test-network:
    driver: bridge
    ipam:
     config:
        - subnet: 192.168.102.1/28
    
